services:
  backend:
    container_name: backend-core-backend

    image: ghcr.io/message-broker-celula/backend-core:latest

    env_file:
      - .env

    ports:
      - "8000:8000"

    restart: unless-stopped

    tty: true